name: api-tests-report
on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (using latest Node.js version)
        uses: actions/checkout@v3  # Upgrade to the latest checkout action

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests and generate report
        run: |
          mkdir -p ./report  # Ensure the report directory exists
          pytest tests.py --html=./report/report.html -o log_file=./report/log.txt

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-tests-report
          path: ./report
