name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html

    - name: Run tests
      run: |
        pytest tests.py --html=report.html -o log_cli=true -o log_cli_level=INFO

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html
